# Demo Catalog metadata — parsed by sync agent

title: Prompt Recipe Cards

pitch: Institutional memory for AI expertise—capture, refine, and share prompt patterns that actually work.

status: live

category: productivity

platform: lovable

featured: false

demo_video:

cover_prompt: A clean, modern dashboard showing organized recipe cards with AI icons, knowledge flow diagrams, and team collaboration elements in a warm, professional color palette.
