// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdyltlumdsgdhyjneeui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkeWx0bHVtZHNnZGh5am5lZXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTAwMzQsImV4cCI6MjA2NDAyNjAzNH0.5GUCyb75lMwOoNpXVoUBKG3hF7CpTbxQTO6sJ500wWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);